
name: Generate snake animation

on:
  schedule:
    - cron: "0 */24 * * *" 
  
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Fetch HEAD
        uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake_animation/github-contribution-grid-snake.svg
            snake_animation/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      - name: Commit and push changes
        run: |
          # https://github.com/actions/checkout/discussions/479
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add snake_animation/github-contribution-grid-snake.svg
          git add snake_animation/github-contribution-grid-snake-dark.svg?palette=github-dark
          git commit -m "Update snake animation"
          git push   
